### ISSUE TITLE
Python versions, woes

### ISSUE THREAD

**Issue by hexagon5un** [xobs/ecp5-toolchain#1] opened 2019-10-07 18:55 UTC
It doesn't look like there's a Python binary in the bundle.  It was using my system's Python (3.7) and causing all sorts of environment trouble.

The workaround was to set PYTHONHOME and PYTHONPATH to point at the ecp5's python libs, but this won't work for anyone who doesn't have Python already installed.

**Comment by xobs** [comment] 2019-10-08 04:15
nextpnr-ecp5 has its own python interpreter linked in.

For Linux, we can't tell if you're on musl or glibc, and python is extremely difficult to statically link. So for now I'm assuming Linux users will install their own python.

I provide python on Darwin, because the system library is stable there and works on 10.10+. I have python on Windows, even though the one from python.org is broken when it comes to packaging.

Do you know of a python distribution that works on musl and across glibc versions?

**Comment by macegr** [comment] 2019-11-10 05:39
Yeah, the linked-in version is not really working well. It doesn't work on a system with Python 3.7 and to use the toolchain's version requires manually adding the path to every module it needs, by process of elimination over several cycles of errors. Running it on a full system with Python 3.7 and a bare bones Docker image with no Python at all has the same result.

By manually tweaking paths it's possible to get nextpnr to run, but it feels like a setup that will explode at the slightest disturbance. I got it running enough to use the built in Python interpreter to print out its search paths, and it's not looking in the right places. Also, it's not trying to use the system's Python installation if present.
```
root@1bcdf350c5a2:/toolchain/bin# export PYTHONPATH="/toolchain/lib/python3.5:/toolchain/lib/python3.5/lib-dynload:/toolchain/lib/python3.5/site-packages:/toolchain/lib/python3.5/plat-x86_64-linux-gnu"
root@1bcdf350c5a2:/toolchain/bin# echo -e "import sys\ntype(sys.path)\nfor path in sys.path:\n  print(path)" > test.py
root@1bcdf350c5a2:/toolchain/bin# nextpnr-ecp5 -f --run test.py
Warning: Use of default value for --package is deprecated. Please add '--package CABGA381' to arguments.
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
/toolchain/bin/.
/toolchain/lib/python3.5
/toolchain/lib/python3.5/lib-dynload
/toolchain/lib/python3.5/site-packages
/toolchain/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/lib-dynload
1 warning, 0 errors
```

**Comment by macegr** [comment] 2019-11-10 05:44
Tweaking the PYTHONHOME value removes some of the references to Python 3.6 and error messages:
```
root@1bcdf350c5a2:/toolchain/bin# export PYTHONHOME="/toolchain/lib/python3.5"
root@1bcdf350c5a2:/toolchain/bin# nextpnr-ecp5 -f --run test.py
Warning: Use of default value for --package is deprecated. Please add '--package CABGA381' to arguments.
/toolchain/bin/.
/toolchain/lib/python3.5
/toolchain/lib/python3.5/lib-dynload
/toolchain/lib/python3.5/site-packages
/toolchain/lib/python3.5/plat-x86_64-linux-gnu
/toolchain/lib/python3.5/lib/python36.zip
/toolchain/lib/python3.5/lib/python3.6
/toolchain/lib/python3.5/lib/python3.6/lib-dynload
```
PYTHONHOME should obviously be set to /toolchain, and it will start searching in /toolchain/lib/python3.6....but we only have python3.5 in this release.

But doing something like removing one of the hand-tweak path additions makes it fall apart again:
```
root@1bcdf350c5a2:/toolchain/bin# export PYTHONPATH="/toolchain/lib/python3.5:/toolchain/lib/python3.5/lib-dynload:/toolchain/lib/python3.5/site-packages"
root@1bcdf350c5a2:/toolchain/bin# nextpnr-ecp5 -f --run test.py
Warning: Use of default value for --package is deprecated. Please add '--package CABGA381' to arguments.
Failed to import the site module
Traceback (most recent call last):
  File "/toolchain/lib/python3.5/site.py", line 580, in <module>
    main()
  File "/toolchain/lib/python3.5/site.py", line 566, in main
    known_paths = addusersitepackages(known_paths)
  File "/toolchain/lib/python3.5/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/toolchain/lib/python3.5/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/toolchain/lib/python3.5/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/toolchain/lib/python3.5/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/toolchain/lib/python3.5/sysconfig.py", line 538, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/toolchain/lib/python3.5/sysconfig.py", line 410, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/toolchain/lib/python3.5/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ModuleNotFoundError: No module named '_sysconfigdata_m'
```

**Comment by macegr** [comment] 2019-11-10 05:47
So it looks like part of the problem is that nextpnr is using Python 3.6 but the libraries in the release are Python 3.5.

**Comment by xobs** [comment] 2019-11-11 04:49
Thanks for reporting this!

The issue was caused by a shift to Ubuntu 18.04.  Python there is 3.6, but I didn't update the libraries that got installed.

This was fixed in https://github.com/xobs/toolchain-nextpnr-ecp5/commit/eaaabbebc35cc4d3910ccf2d042cc0ddc2394e9b and I added a note in https://github.com/xobs/toolchain-nextpnr-ecp5/commit/eaaabbebc35cc4d3910ccf2d042cc0ddc2394e9b describing what needs to be done to update Python.

I'll re-release `ecp5-toolchain` once those packages have been rebuilt.

**Comment by xobs** [comment] 2019-11-11 05:02
Can you see if v1.6.2 solves the issue? https://github.com/xobs/ecp5-toolchain/releases/tag/v1.6.2

**Comment by macegr** [comment] 2019-11-11 07:16
I can confirm that 1.6.2 does work without juggling environment variables, I would consider this fixed. Due to trying this in a container, every image build is essentially a fresh machine so I'm confident your changes made the difference rather that some unknown config tweak or package versioning elsewhere.

**Comment by xobs** [comment] 2019-11-11 18:28
Thanks for finding the source of the issue!

**Closed as completed by xobs** 2019-11-11 18:28 UTC
